version: '3.4'
services:
  liveness-api:
    build: .
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./app:/var/www/face-recognition-liveness/app
    
    labels:
      - "autoheal=true"

    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 1
      start_period: 20s
      timeout: 10s
  
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - AUTOHEAL_INTERVAL=10
      - CURL_TIMEOUT=30